//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ДорожноеПриложение
{
    using System;
    using System.Collections.Generic;
    
    public partial class Задачи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Задачи()
        {
            this.СписокРасходов = new HashSet<СписокРасходов>();
        }
    
        public int КодЗадачи { get; set; }
        public string ЗадачаНаз { get; set; }
        public string Место { get; set; }
        public int Бригада { get; set; }
        public string Статус { get; set; }
        public string Отчет { get; set; }
        public int Категория { get; set; }
        public System.DateTime Дата { get; set; }
    
        public virtual Бригады Бригады { get; set; }
        public virtual Категории Категории { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СписокРасходов> СписокРасходов { get; set; }
    }
}
