//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ДорожноеПриложение
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ДорожнаяБазаEntities : DbContext
    {
        private static ДорожнаяБазаEntities DBE = null;

        public static ДорожнаяБазаEntities GetДорожнаяБазаEntities()
        {
            if (DBE == null)
                DBE = new ДорожнаяБазаEntities();

            return DBE;
        }

        public ДорожнаяБазаEntities()
            : base("name=ДорожнаяБазаEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Бригады> Бригады { get; set; }
        public virtual DbSet<Задачи> Задачи { get; set; }
        public virtual DbSet<Категории> Категории { get; set; }
        public virtual DbSet<СкладМатериала> СкладМатериала { get; set; }
        public virtual DbSet<Сотрудники> Сотрудники { get; set; }
        public virtual DbSet<СписокРасходов> СписокРасходов { get; set; }
    }
}
