//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ДорожноеПриложение
{
    using System;
    using System.Collections.Generic;
    
    public partial class СкладМатериала
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public СкладМатериала()
        {
            this.СписокРасходов = new HashSet<СписокРасходов>();
        }
    
        public int КодМатериала { get; set; }
        public string МатериалНаз { get; set; }
        public double Количиство { get; set; }
        public string ЕденицаИзмерения { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СписокРасходов> СписокРасходов { get; set; }
    }
}
